### ISSUE TITLE
Volume attachment status in the VolumeStatus API

### ISSUE THREAD

**Issue by hardikdr** [onmetal/onmetal-api#383]
# Summary

It would be of use to be able to post the Attach Status of the Volume in the Machine. Currently, following seems to be available API:

```go
// VolumeStatus is the status of a Volume.
type VolumeStatus struct {
	// Name is the name of a volume attachment.
	Name string
	// DeviceID is the disk device ID on the host.
	DeviceID string
}
```

## Basic example

```go
// VolumeStatus is the status of a Volume.
type VolumeStatus struct {
	// Name is the name of a volume attachment.
	Name string
	// DeviceID is the disk device ID on the host.
	DeviceID string
        // AttachStatus is the status if the disk is attached.
        AttachStatus string // better name may be. Attached, Error, Pending.
}
```

## Motivation

Irrespective of the health of the Volume, the attachment status with the Machine could differ. Such a field should help convey such status information. 
Open for further discussions.

**Comment by adracus** [comment]
Implemented in ee847221a1ddb231f31224a0cdb5c250f7545960
